vich_uploader:
    db_driver: orm

    mappings:
       poster_file:
            uri_prefix: /images/posters
            upload_destination: '%kernel.project_dir%/public/images/posters'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
